### ISSUE TITLE
[regression] 11.2.1 doesn't work with React Native

### ISSUE THREAD

**Issue by piranna** [legastero/stanza.io#331]
Stanza 11.1.1 works flawless in React Native by using the [node-libs-react-native](https://www.npmjs.com/package/node-libs-react-native) dependency to add the missing global definitions, but after upgrading to Stanza 11.2.1, I get the next error:

```javascript
error: bundling failed: Error: Unable to resolve module `vm` from `/home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/asn1.js/lib/asn1/api.js`: Module `vm` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (/home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/metro/src/node-haste/DependencyGraph.js:273:16)
    at Object.resolve (/home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:391:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:388:18)
    at /home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:261:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/piranna/Trabajo/lingbe/app-rn-cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

Seems to be related to the usage of `crypto` module by Stanza, that with `node-libs-react-native` it's implemented with [react-native-crypto](https://www.npmjs.com/package/react-native-crypto). The `asn1.js` dependency is being used by [parse-asn1](https://www.npmjs.com/package/parse-asn1). Have been there any changes related to this? It could be possible to use a pure Javascript alternative to do that operations? Why is `crypto` module needed at all by Stanza?

**Comment by legastero** [comment]
> Why is crypto module needed at all by Stanza?

Hashes, HMACs, and random bytes. All needed for things like authentication mechanisms, entity capabilities, and file transfer checksums.

I tried creating a fresh RN project using stanza and node-libs-react-native. I got it to work, but only when the client happened to avoid using anything crypto related (especially random bytes) when running, like by using PLAIN authentication instead of something like SCRAM-SHA-1. So v11.1.1 wasn't flawless with RN, it just blew up at run time instead of build time.

The way I've always set up RN with stanza in the past was by using `rn-nodeify`, but that's a rather messy thing to use.

It looks like `node-libs-react-native` is explicitly not providing a `vm` implementation, which `react-native-crypto` is requiring. The `rn-nodeify` module did provide a `vm` implementation with `vm-browserify`.

So these are the changes I made in my RN project to get things working:

```sh
npm i react-native-crypto react-native-randombytes vm-browserify
react-native link react-native-randombytes
```

`metro.config.js`:
```js
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  resolver: {
      extraNodeModules: {
          ...require('node-libs-react-native'),
          vm: require.resolve('vm-browserify')
      }
  }
};
```

**Comment by legastero** [comment]
Looks like there's a PR already for `node-libs-react-native` to fix this nicely, eventually: https://github.com/parshap/node-libs-react-native/pull/17

**Comment by marcelolx** [comment]
Any of you @piranna or @legastero can provide a simple react-native project with stanza.io? What steps i need do to to put working?

**Comment by legastero** [comment]
@marcelolx https://github.com/legastero/stanza.io/blob/master/docs/React_Native.md
